stages:
  - lint
  - typecheck
  - build

lint:
  image: node:latest
  stage: lint
  script:
    - yarn
    - yarn lint

typecheck:
  image: node:latest
  stage: typecheck
  script:
    - yarn
    - yarn typecheck

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.uniqsoft.pl/time-tracking --build-arg INFISICAL_API_URL --build-arg INFISICAL_TOKEN .
    - docker login -u -p https://registry.uniqsoft.pl
    - docker push registry.uniqsoft.pl/time-tracking