-- AlterTable
ALTER TABLE "TimeCard" ALTER COLUMN "start" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "start" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "end" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "TimeLog" ALTER COLUMN "start" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "start" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "end" SET DATA TYPE TIMESTAMP(3);
